### ISSUE TITLE
resource packs getting reset

### ISSUE THREAD

**Issue by Aces-and-Jacks** [Tectato/Telepistons#12]
Every time I launch Minecraft my resource packs keep getting reset and when I disable this mod it stops reseting. So I think this mod resets my resource packs

**Comment by Aces-and-Jacks** [comment]
https://mclo.gs/0XGcKkS

**Comment by Tectato** [comment]
Seems like an incompatibility with respackopts, I'm looking into it

**Comment by Tectato** [comment]
Nevermind that's not it. Could you try loading the game just with Telepistons and the fabric API installed? If you're using a public modpack could you also send me a link so I can do some testing with that set of mods myself?

**Comment by Aces-and-Jacks** [comment]
It works normally. do you want the log?

**Comment by Aces-and-Jacks** [comment]
well respackopt isn't really useful so I can just disable it

**Comment by Aces-and-Jacks** [comment]
removed the mod and still resets it

**Comment by Tectato** [comment]
yeah the issue is one of the other hundreds of mods, thats why a link to the modpack would be useful if it's a public one

**Comment by Aces-and-Jacks** [comment]
yeah sorry didn't see that you already said that. unfortunately its a bunch of mods I bunched together and isn't a public modpack

**Comment by Aces-and-Jacks** [comment]
i can try disabling other mods till i find out which mod it is but it'll take a while

**Comment by Aces-and-Jacks** [comment]
it's libjf

**Comment by Aces-and-Jacks** [comment]
which respackopt required as a dependency which may be why you thought it was that at first

**Comment by Tectato** [comment]
I tried launching the game with just cloth config, fabric API, libjf, respackopts, and telepistons and that worked just fine on my end. It does reload resources twice at the very start but after that it catches itself and doesn't do that again

**Comment by Aces-and-Jacks** [comment]
oh. then never mind. I can try again and see if that's the issue. If not I can check again but it'll take a bit

**Comment by Aces-and-Jacks** [comment]
well I tried it with cloth config, fabric API, libjf, respackopts, telepistons, Mod Menu, and LazyDFU and no matter how many times a launch minecraft my resource packs keep on resetting. Not sure if your system is just different but that's what happens for me

**Comment by Aces-and-Jacks** [comment]
Tried launching on my normal modpack and so far works fine. I'll reopen this if the issue comes up again

**Comment by Tectato** [comment]
Can you provide a log?
