### ISSUE TITLE
As of TelePistons 1.1.0, `particles=0` in `telepistons.properties` is no longer respected. There is now no longer a way to disable steam particles upon piston state change with the default mod-provided model.

### ISSUE THREAD

**Issue by akemin-dayo** [Tectato/Telepistons#3]
As of TelePistons 1.1.0, `particles=0` in `telepistons.properties` is no longer respected.

This means that there is now no longer a way to disable steam particles upon piston state change with the default mod-provided model. (In other words, without a resource pack.)

(Seems like TelePistons 1.1.0 no longer reads that config file anymore due to all configuration being moved to being resource-pack-based?)

… Also, the source code available here on GitHub appears to be rather out of date.

(I'd also suggest disabling steam particles by default, since I think most people using TelePistons expect Bedrock behaviour, where there are no particles.)

**Comment by Tectato** [comment]
Good point, I've added a pack for overriding the particle settings, active by default
