### ISSUE TITLE
In TelePistons 1.1.1, the `telepistons/no_steam` resource pack is not actually enabled by default despite being declared as such.

### ISSUE THREAD

**Issue by akemin-dayo** [Tectato/Telepistons#4]
This issue is occurring with both Quilt and Fabric. (And if I remember correctly, I think Fabric doesn't actually support enabling mod-provided resource packs by default, as that was new functionality introduced with Quilt…?)

I'd recommend perhaps instead inverting the behaviour — require a resource pack of `telepistons/steam_particles` to be explicitly enabled in order to show steam particles upon piston state change, so a user that has no resource packs enabled at all would have behaviour that matches Bedrock.

**Comment by Tectato** [comment]
Fair enough, behaviour has been inverted. My fault for not reading the documentation more carefully i suppose
