### ISSUE TITLE
Conflict with crowdin translate

### ISSUE THREAD

**Issue by supersaiyansubtlety** [Tectato/Telepistons#5]
Somehow 1.1.1a seems to be breaking crowdin translate.
When telepistons and any of my mods that bundle crowdin translate are installed together, I get a crash on game launch.

quilt, 1.19

crash report: https://paste.myst.rs/zj40ha0l
log: https://paste.myst.rs/2xx0c9lh

**Comment by Tectato** [comment]
Looks like the 'a' at the end is throwing it off, does 1.1.1 work? I can't get _Camp fires cook mobs_ to run on its own and don't know any other mods that use crowdin translate to test myself

**Comment by supersaiyansubtlety** [comment]
Appears to be the same with 1.1.1
log: https://paste.myst.rs/v93v1459

**Comment by supersaiyansubtlety** [comment]
What kind of issue are you having with campfires cook mobs?
If appropriate, could you please open an issue? https://gitlab.com/supersaiyansubtlety/camp_fires_cook_mobs/-/issues

**Comment by ruvaldak** [comment]
I'm getting the same thing, but instead of crashing, it just constantly repeats the error, disabling all resource packs.

**Comment by supersaiyansubtlety** [comment]
I suspect that's a mod interaction

With all my mods enabled, instead of crashing it hangs on startup, with the mojang screen progress bar resetting over and over again.

**Comment by ruvaldak** [comment]
Errors I'm getting are very similar to yours - including the mention of crowdin translate. 1 moment and I'll post a log.

**Comment by ruvaldak** [comment]
https://mclo.gs/2XltDhY

**Comment by Tectato** [comment]
> What kind of issue are you having with campfires cook mobs? If appropriate, could you please open an issue? https://gitlab.com/supersaiyansubtlety/camp_fires_cook_mobs/-/issues

It crashes telling me that version 7.0.72 of cloth-config2 is required, even though i did install the version linked to on the curseforge page. Not sure if opening an issue for that is appropriate since it seems to work on your end

**Comment by Tectato** [comment]
> https://mclo.gs/2XltDhY

That's a lot of "Error loading class" from a variety of mods, do these errors really not happen without Telepistons installed?

**Comment by Tectato** [comment]
Running the game with Telepistons and [Sync](https://modrinth.com/mod/sync-fabric), another mod using Crowdin Translate, works just fine for me, how about you?

**Comment by Tectato** [comment]
Does the issue persist in 1.1.2?

**Comment by ruvaldak** [comment]
seems fixed now.
